name: Agendador

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
 
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v2

      - name: Instalar dependências
        run:  
          R -e 'install.packages("tsibble")'
          R -e 'install.packages("zoo")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("readr")'

      - name: Executar código
        run: Rscript R modelagem/garch_forecast.R
