name: Agendador

on:
  schedule:
    - cron: '00 15 * * *' 

jobs:
  scrape:
    runs-on: macos-latest

    steps:
 
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v2

      - name: Instalar dependências
        run:  
          R -e 'install.packages("tsibble")'
          R -e 'install.packages("zoo")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("quantmod")'

      - name: Executar código
        run: Rscript modelagem/garch_forecast.R
      - name: Debug
        run: ls -R  
      - name: Commit
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add --all
          git commit -am "add Data"
          git push
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
 
