name: Agendador

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master 

      - name: Instalar dependências
        run: |
          R -e 'install.packages("ggfortify")'
          R -e 'install.packages("fpp3")'
          R -e 'install.packages("dygraphs")'
          R -e 'install.packages("tsibble")'
          R -e 'install.packages("zoo")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("forecast")'
          R -e 'install.packages("readr")'

      - name: Executar código
        run: Rscript R modelagem/garch_forecast.R
